# Generated by Django 4.0.4 on 2022-05-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JWT', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50, verbose_name='username')),
                ('profilePic', models.CharField(max_length=255, verbose_name='avatar')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
