# Generated by Django 4.0.4 on 2022-05-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rules', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('type', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='rooms.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_entries', to='users.user')),
            ],
        ),
    ]
