# Generated by Django 4.0.4 on 2022-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomentry',
            name='day',
        ),
        migrations.AlterField(
            model_name='roomentry',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
