# Generated by Django 4.0.4 on 2022-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_roomentry_day_alter_roomentry_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomentry',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
