# Generated by Django 4.0.4 on 2022-05-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laundry_entries', to='users.user'),
        ),
    ]
